.TL
Speedlines Generation Tool for Compositors
.AU
Kristiyan Aladjov
.AB
This is where the abstract goes.
.AE
.NH
Introduction
.PP
Intro paragraph

.NH
Context
.PP
Related work

.NH
Hypothesis
.PP
General idea behindthe project

.NH
Process
.PP
How the results were achieved

.NH
Analysis
.PP
Critical evaluation of the process and the hypo

.NH
Conclusion
.PP
Final words and future work.

.NH
References
